// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(EsiDbContext))]
    [Migration("20220201073506_V2022_02_01_1104")]
    partial class V2022_02_01_1104
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("DataLayer.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppFoods")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cod_Contract_Order")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cod_Coupon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cod_Meal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cod_Resturant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cod_Serial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dat_Day_Mepdy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTime_SentToWebService")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date_Use")
                        .HasColumnType("TEXT");

                    b.Property<string>("Des_Contract_Order")
                        .HasColumnType("TEXT");

                    b.Property<string>("Des_Food_Order_Mepdy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Des_Nam_Meal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Des_Nam_Resturant_Rstm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Employee_Shift_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("First_Name_Ide")
                        .HasColumnType("TEXT");

                    b.Property<string>("Last_Name_Ide")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lkp_Cod_Order_Mepdy_Means")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainFood")
                        .HasColumnType("TEXT");

                    b.Property<string>("Meal_Plan_Day_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Num_Ide")
                        .HasColumnType("TEXT");

                    b.Property<string>("Num_Tim_End_Meal_Rsmls")
                        .HasColumnType("TEXT");

                    b.Property<string>("Num_Tim_Str_Meal_Rsmls")
                        .HasColumnType("TEXT");

                    b.Property<string>("Num_Tot_Coupon_Rccpn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Receiver_Meal_Plan_Day_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reciver_Coupon_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Time_Use")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Cod_Meal", "Reciver_Coupon_Id", "Num_Ide");

                    b.ToTable("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
